apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  serviceName: "alertmanager"
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "prom/alertmanager:v0.18.0"
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --web.external-url=/
          ports:
            - containerPort: 9093
              name: http
          readinessProbe:
            httpGet:
              path: "/#/status"
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
        - name: configmap-reload
          image: "jimmidyson/configmap-reload:v0.1"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9093/-/reload
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 10Mi
            requests:
              cpu: 50m
              memory: 10Mi
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager
  type: NodePort
