---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global: null
    receivers:
    - name: slack-receiver
      slack_configs:
      - api_url: https://some-slack-api-url
        send_resolved: true
        channel: '#infraut-notifications'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]'
        text: |-
          *Alert Details:*
          {{ range .GroupLabels.SortedPairs }}
          - *{{ .Name }}:* {{ .Value }}
          {{ end }}
          *Message:*
          {{ range .Alerts }}
            - {{ .Annotations.message }}
          {{ end }}
          {{ (index .Alerts 0).Annotations.runbook_url }}
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-receiver
      repeat_interval: 5h
      group_by: [cluster,alertname,severity]
