{
 "title": "Kubernetes / ClusterView",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (nodename) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_load1) by (nodename) * 100) / count(node_cpu_seconds_total{mode=\"system\"}) by (nodename)",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes) by (nodename) \n/ sum(node_memory_MemTotal_bytes) by (nodename)) * 100",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1- sum(node_filesystem_free_bytes{mountpoint=\"/\",fstype=\"xfs\"}) by (nodename, mountpoint) / sum(node_filesystem_size_bytes{mountpoint=\"/\",fstype=\"xfs\"}) by (nodename, mountpoint)) * 100",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kube_node_status_allocatable_cpu_cores"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "(floor(kube_node_status_capacity_memory_bytes * 100)/ 100) - 637203200"
    }
   ]
  },
  {
   "title": "Sockets in Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_sockstat_sockets_used) by (nodename)",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "Available Cpus (Requests) by Nodes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_cpu_cores) by (node) - sum(kube_pod_container_resource_requests_cpu_cores) by (node) )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "TCP Open Connections",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sort(sum(node_netstat_Tcp_CurrEstab) by (nodename))"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"ens.*\"}[5m])*8",
     "legendFormat": "{{ nodename }} - ({{device}})_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"ens.*\"}[5m])*8",
     "legendFormat": "{{ nodename }} - ({{device}})_out"
    }
   ]
  },
  {
   "title": "Allocatable Memory vs Memory Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "(sum(kube_node_status_allocatable_memory_bytes/(1024*1024*1024) ) by (node) - sum(kube_pod_container_resource_requests_memory_bytes/(1024*1024*1024)) by (node) )",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "cluster=${cluster}", "labelSelector": "*", "target": "Query", "type": "table" }
   ]
  }
 ]
}